"""empty message

Revision ID: 67b32d09a7d0
Revises: 
Create Date: 2026-01-18 13:13:25.524459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b32d09a7d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_psel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_podio', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('aiesec_mais_proxima', sa.String(length=255), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('expiracao', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_podio'),
    sa.UniqueConstraint('token')
    )
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['lead_psel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['lead_psel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telefone')
    op.drop_table('email')
    op.drop_table('lead_psel')
    # ### end Alembic commands ###
