from ..config import (AMBIENTE, DOMINIOS_PRODUCAO,DOMINIOS_TESTE,
                      DB_PRODUCAO,DB_TESTE,URL_PRODUCAO,URL_TESTE)

IS_PRODUCTION: bool = AMBIENTE in {"PRODUCTION", "PROD"}
IS_NON_PROD: bool = AMBIENTE in {"DEVELOPMENT", "DEV", "TEST", "TESTING"}

if not (IS_PRODUCTION or IS_NON_PROD):
    raise ValueError(f"Ambiente inválido: {AMBIENTE}")

if IS_PRODUCTION:
    DOMINIOS_PERMITIDOS = [f"https://{dominio}" for dominio in DOMINIOS_PRODUCAO]
else:
    DOMINIOS_PERMITIDOS = [f"https://{dominio}" for dominio in DOMINIOS_TESTE]

DB_CONNECT = DB_PRODUCAO if IS_PRODUCTION else DB_TESTE
URL_CONNECT= URL_PRODUCAO if IS_PRODUCTION else URL_TESTE

__all__ = [
    "DOMINIOS_PERMITIDOS",
    "URL_CONNECT",
    "DB_CONNECT",
    "IS_PRODUCTION",
    "IS_NON_PROD"
]